### ISSUE TITLE
Is it still recommendable to use SW on Nginx?

### ISSUE THREAD

**Issue by JesusLeon** [bcremer/shopware-with-nginx#31]
Hi @bcremer,

nice to find an unofficial repository of configurations for nginx from an official Shopware Tech member. 

My question is, even so, do you (or is it) still recommended to use Shopware on Nginx, regardless of the official support? Is it reliable? What are the most common examples of something that can go wrong?

Thanks.

**Comment by emilv** [comment]
One thing that concerns me is that file access is limited with a blacklist instead of a whitelist. For example, the configuration blocks access to `autoload.php` but not `autload.php.backup`.

This is an issue with the Apache .htaccess too. But the issue on Nginx is that it will always lag behind changes to the Apache configuration. If Shopware makes changes to .htaccess you might forget to update your Nginx config.

Ideally it should be more like in Laravel where only a certain folder is accessible at all, say, `public/`, and only a single file is interpreted as PHP, say, `shopware.php`. That would allow a safer and also easier web server configuration.

**Comment by emilv** [comment]
Apart from that, Shopware runs fine on Nginx with the config from this repo.

**Comment by JesusLeon** [comment]
@emilv good point.
